import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { LoginProvider } from "@/components/context/LoginContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs Blogger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-200`}>
        <LoginProvider>
          <Navbar />
          {children}
        </LoginProvider>
      </body>
    </html>
  );
}
